version: '3.8'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    environment:
      AUTH: 'yes'
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret071
      MONGO_INITDB_DATABASE: salary
    volumes:
      - ./data/mongo_db:/data/db
    ports:
      - '27017:27017'
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret071
      - MYSQL_DATABASE=salary
    volumes:
      - ./data/mysql_db:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - '8081:80'
  server_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: server_node
    restart: unless-stopped
    environment:
      - NODE_ENV=prod
    volumes:
      - ./src:/src
      - /src/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mysql_db
      - mongo_db
    networks:
      - net_com
  nignx_proxy:
    container_name: nignx_proxy
    restart: unless-stopped
    image: nginx
    build: .
    ports:
      - '80:80'
    depends_on:
      - server_node
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net_com

networks:
  net_com:
    driver: bridge
