version: '2'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    environment:
      AUTH: 'yes'
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret071
      MONGO_INITDB_DATABASE: salary
    volumes:
      - ./data/mongo_db:/data/db
    ports:
      - '27017:27017'
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret071
      - MYSQL_DATABASE=salary
    volumes:
      - ./data/mysql_db:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - '8081:80'
  salary_web:
    image: node:latest
    container_name: salary_web
    volumes:
      - ./src:/src
      - /src/node_modules
    command: sh -c "npm install -g nodemon && cd /src && npm install && npm run dev"
    ports:
      - "3000:3000"